<? require($_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/main/include/prolog_before.php");
$APPLICATION->SetTitle("");

if (! \Bitrix\Main\Loader::includeModule('nextype.corporate') )
    exit();
?><?$APPLICATION->IncludeComponent(
	"nextype:corporate.forms.pro",
	"popup",
	Array(
		"CAPTCHA" => "N",
		"FIELDS" => "W3sibGFiZWwiOiJcdTA0MjQuXHUwNDE4Llx1MDQxZS4iLCJuYW1lIjoiTkFNRSIsInR5cGUiOiJ0ZXh0IiwicmVxdWlyZWQiOiJZIiwiZGVmYXVsdCI6IiIsInZhbHVlcyI6IiIsIm1hc2siOiIiLCJzb3J0IjoiMTAwIn0seyJsYWJlbCI6Ilx1MDQxYVx1MDQzZVx1MDQzZFx1MDQ0Mlx1MDQzMFx1MDQzYVx1MDQ0Mlx1MDQzZFx1MDQ0Ylx1MDQzOSBcdTA0NDJcdTA0MzVcdTA0M2JcdTA0MzVcdTA0NDRcdTA0M2VcdTA0M2QiLCJuYW1lIjoiUEhPTkUiLCJ0eXBlIjoidGV4dCIsInJlcXVpcmVkIjoiWSIsImRlZmF1bHQiOiIiLCJ2YWx1ZXMiOiIiLCJtYXNrIjoiKzcgKCMjIykgIyMjLSMjLSMjIiwic29ydCI6IjIwMCJ9LHsibGFiZWwiOiJcdTA0MTJcdTA0MzBcdTA0NDhcdTA0MzAgXHUwNDNmXHUwNDNlXHUwNDQ3XHUwNDQyXHUwNDMwIiwibmFtZSI6IkVNQUlMIiwidHlwZSI6ImVtYWlsIiwicmVxdWlyZWQiOiJZIiwiZGVmYXVsdCI6IiIsInZhbHVlcyI6IiIsIm1hc2siOiIiLCJzb3J0IjoiMzAwIn0seyJsYWJlbCI6Ilx1MDQxNlx1MDQzNVx1MDQzYlx1MDQzMFx1MDQzNVx1MDQzY1x1MDQzMFx1MDQ0ZiBcdTA0MzRcdTA0M2VcdTA0M2JcdTA0MzZcdTA0M2RcdTA0M2VcdTA0NDFcdTA0NDJcdTA0NGMiLCJuYW1lIjoiSk9CIiwidHlwZSI6InRleHQiLCJyZXF1aXJlZCI6IlkiLCJkZWZhdWx0IjoiPXskX1JFUVVFU1RbXHUwMDI3Sk9CXHUwMDI3XX0iLCJ2YWx1ZXMiOiIiLCJtYXNrIjoiIiwic29ydCI6IjQwMCJ9LHsibGFiZWwiOiJcdTA0MWVcdTA0M2ZcdTA0NGJcdTA0NDIgXHUwNDQwXHUwNDMwXHUwNDMxXHUwNDNlXHUwNDQyXHUwNDRiIiwibmFtZSI6IkVYUEVSSUVOQ0UiLCJ0eXBlIjoidGV4dGFyZWEiLCJyZXF1aXJlZCI6IlkiLCJkZWZhdWx0IjoiIiwidmFsdWVzIjoiIiwibWFzayI6IiIsInNvcnQiOiI1MDAifSx7ImxhYmVsIjoiXHUwNDFhXHUwNDNlXHUwNDNjXHUwNDNjXHUwNDM1XHUwNDNkXHUwNDQyXHUwNDMwXHUwNDQwXHUwNDM4XHUwNDM5IiwibmFtZSI6IkNPTU1FTlQiLCJ0eXBlIjoidGV4dGFyZWEiLCJyZXF1aXJlZCI6IlkiLCJkZWZhdWx0IjoiIiwidmFsdWVzIjoiIiwibWFzayI6IiIsInNvcnQiOiI2MDAifV0=",
		"FORM_DESCRIPTION" => "",
		"FORM_TITLE" => "Отклик на вакансию",
		"MESSAGE_ERRORALL" => "",
		"MESSAGE_SUCCESS" => "Ваш отклик на вакансию успешно отправлен!",
		"NAME" => "Форма Отклик на вакансию",
		"PERSONAL_PROCESSING" => "Y",
		"PERSONAL_PROCESSING_PAGE" => "/agreement/",
		"SEND_EMAIL_ADDRESS" => "sale@santehnic-market.ru",
		"SEND_EMAIL_ENABLED" => "Y",
		"SEND_EMAIL_EVENT_NAME" => "",
		"SEND_IBLOCK_ENABLED" => "N",
		"SUBMIT_BUTTON_TEXT" => "Отправить",
		"VIEW_TYPE" => ""
	)
);?>