<?$APPLICATION->IncludeComponent(
	"nextype:corporate.forms.pro",
	"feedback",
	Array(
		"CAPTCHA" => "N",
		"FIELDS" => "W3sibGFiZWwiOiJcdTA0MjQuXHUwNDE4Llx1MDQxZS4iLCJuYW1lIjoiTkFNRSIsInR5cGUiOiJ0ZXh0IiwicmVxdWlyZWQiOiJZIiwiZGVmYXVsdCI6IiIsInZhbHVlcyI6IiIsIm1hc2siOiIiLCJzb3J0IjoiMTAwIn0seyJsYWJlbCI6Ilx1MDQxYVx1MDQzZVx1MDQzZFx1MDQ0Mlx1MDQzMFx1MDQzYVx1MDQ0Mlx1MDQzZFx1MDQ0Ylx1MDQzOSBcdTA0NDJcdTA0MzVcdTA0M2JcdTA0MzVcdTA0NDRcdTA0M2VcdTA0M2QiLCJuYW1lIjoiUEhPTkUiLCJ0eXBlIjoidGV4dCIsInJlcXVpcmVkIjoiWSIsImRlZmF1bHQiOiIiLCJ2YWx1ZXMiOiIiLCJtYXNrIjoiKzcgKCMjIykgIyMjLSMjLSMjIiwic29ydCI6IjIwMCJ9LHsibGFiZWwiOiJcdTA0MTJcdTA0MzBcdTA0NDhcdTA0MzAgXHUwNDNmXHUwNDNlXHUwNDQ3XHUwNDQyXHUwNDMwIiwibmFtZSI6IkVNQUlMIiwidHlwZSI6ImVtYWlsIiwicmVxdWlyZWQiOiJZIiwiZGVmYXVsdCI6IiIsInZhbHVlcyI6IiIsIm1hc2siOiIiLCJzb3J0IjoiMzAwIn0seyJsYWJlbCI6Ilx1MDQxYVx1MDQzZVx1MDQzY1x1MDQzY1x1MDQzNVx1MDQzZFx1MDQ0Mlx1MDQzMFx1MDQ0MFx1MDQzOFx1MDQzOSIsIm5hbWUiOiJNRVNTQUdFIiwidHlwZSI6InRleHRhcmVhIiwicmVxdWlyZWQiOiJZIiwiZGVmYXVsdCI6IiIsInZhbHVlcyI6IiIsIm1hc2siOiIiLCJzb3J0IjoiNDAwIn1d",
		"FORM_DESCRIPTION" => "",
		"FORM_TITLE" => "Обратная связь",
		"MESSAGE_ERRORALL" => "",
		"MESSAGE_SUCCESS" => "Ваше сообщение успешно отправлено!",
		"NAME" => "Обратная связь",
		"PERSONAL_PROCESSING" => "Y",
		"PERSONAL_PROCESSING_PAGE" => "/agreement/",
		"SEND_EMAIL_ADDRESS" => "",
		"SEND_EMAIL_ENABLED" => "Y",
		"SEND_EMAIL_EVENT_NAME" => "",
		"SEND_IBLOCK_ENABLED" => "N",
		"SUBMIT_BUTTON_TEXT" => "Отправить",
		"VIEW_TYPE" => ""
	)
);?>