<?$APPLICATION->IncludeComponent(
	"nextype:corporate.tabs",
	"mainpage_slider",
	Array(
		"ACTION_VARIABLE" => "action",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BACKGROUND_IMAGE" => "-",
		"BASKET_URL" => "/personal/basket.php",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"COMPATIBLE_MODE" => "N",
		"DETAIL_URL" => "",
		"ELEMENT_COUNT" => "8",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER2" => "desc",
		"FILTER_NAME" => "arrFilter",
		"IBLOCK_ID" => \Nextype\Corporate\COptions::getIblockID("catalog"),
		"IBLOCK_PROPERTY_TAGS" => array("NEW","SALE","HIT",""),
		"IBLOCK_TYPE" => "nt_corporate_catalog",
		"INCLUDE_SUBSECTIONS" => "Y",
		"LABEL_PROP" => array("",""),
		"OFFERS_LIMIT" => "5",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRICE_CODE" => array("PRICE"),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPERTIES" => array(),
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"PROPERTY_CODE" => array("ARTICLE","STOCK","OLD_PRICE","PRICE",""),
		"SECTION_CODE_PATH" => "",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SECTION_URL" => "",
		"SEF_MODE" => "Y",
		"SEF_RULE" => "",
		"SHOW_ALL_WO_SECTION" => "Y",
		"SHOW_PRICE_COUNT" => "1",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "N",
            "LINE_ELEMENT_COUNT" => "4",
            "PROPERTY_TAGS" => array(
			0 => "NEW",
			1 => "SALE",
			2 => "HIT",
			3 => "",
		),
            "PROPERTY_PRICE" => "PRICE",
		"PROPERTY_OLD_PRICE" => "OLD_PRICE",
	)
);?>